
Step 1. Go to https://www.kaggle.com/openfoodfacts/world-food-facts/data

Step 2. Download the dataset to your computer and unzip it.

Name: Mona Mashtaa

In [36]:
%pip install kagglehub

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: kagglehub in /home/mona/.local/lib/python3.10/site-packages (1.0.0)
Requirement already satisfied: kagglesdk<1.0,>=0.1.14 in /home/mona/.local/lib/python3.10/site-packages (from kagglehub) (0.1.16)
Requirement already satisfied: pyyaml in /usr/lib/python3/dist-packages (from kagglehub) (5.4.1)
Requirement already satisfied: requests in /usr/lib/python3/dist-packages (from kagglehub) (2.25.1)
Requirement already satisfied: tqdm in /home/mona/.local/lib/python3.10/site-packages (from kagglehub) (4.67.3)
Requirement already satisfied: packaging in /home/mona/.local/lib/python3.10/site-packages (from kagglehub) (26.0)
Requirement already satisfied: protobuf in /home/mona/.local/lib/python3.10/site-packages (from kagglesdk<1.0,>=0.1.14->kagglehub) (7.34.0)
Note: you may need to restart the kernel to use updated packages.

In [37]:
from pathlib import Path
import kagglehub

# Download latest version
path = Path(kagglehub.dataset_download("openfoodfacts/world-food-facts"))

print("Path to dataset files:", path)

Path to dataset files: /home/mona/.cache/kagglehub/datasets/openfoodfacts/world-food-facts/versions/5

In [38]:

data_path = path / "en.openfoodfacts.org.products.tsv"
print(data_path.exists())

True

Step 3. Use the tsv file and assign it to a dataframe called food

In [39]:
import pandas as pd

db_food = pd.read_csv(data_path, sep="\t")
db_food.head()

/tmp/ipykernel_85708/993899533.py:3: DtypeWarning: Columns (0,3,5,19,20,24,25,26,27,28,36,37,38,39,48) have mixed types. Specify dtype option on import or set low_memory=False.
  db_food = pd.read_csv(data_path, sep="\t")

,code,url,creator,created_t,created_datetime,last_modified_t,last_modified_datetime,product_name,generic_name,quantity,...,fruits-vegetables-nuts_100g,fruits-vegetables-nuts-estimate_100g,collagen-meat-protein-ratio_100g,cocoa_100g,chlorophyl_100g,carbon-footprint_100g,nutrition-score-fr_100g,nutrition-score-uk_100g,glycemic-index_100g,water-hardness_100g
0,3087,http://world-en.openfoodfacts.org/product/0000...,openfoodfacts-contributors,1474103866,2016-09-17T09:17:46Z,1474103893,2016-09-17T09:18:13Z,Farine de blé noir,NaN,1kg,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,4530,http://world-en.openfoodfacts.org/product/0000...,usda-ndb-import,1489069957,2017-03-09T14:32:37Z,1489069957,2017-03-09T14:32:37Z,Banana Chips Sweetened (Whole),NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,14.0,14.0,NaN,NaN
2,4559,http://world-en.openfoodfacts.org/product/0000...,usda-ndb-import,1489069957,2017-03-09T14:32:37Z,1489069957,2017-03-09T14:32:37Z,Peanuts,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN
3,16087,http://world-en.openfoodfacts.org/product/0000...,usda-ndb-import,1489055731,2017-03-09T10:35:31Z,1489055731,2017-03-09T10:35:31Z,Organic Salted Nut Mix,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,12.0,12.0,NaN,NaN
4,16094,http://world-en.openfoodfacts.org/product/0000...,usda-ndb-import,1489055653,2017-03-09T10:34:13Z,1489055653,2017-03-09T10:34:13Z,Organic Polenta,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

Step 4. See the first 5 entries

In [40]:
db_food.head()

,code,url,creator,created_t,created_datetime,last_modified_t,last_modified_datetime,product_name,generic_name,quantity,...,fruits-vegetables-nuts_100g,fruits-vegetables-nuts-estimate_100g,collagen-meat-protein-ratio_100g,cocoa_100g,chlorophyl_100g,carbon-footprint_100g,nutrition-score-fr_100g,nutrition-score-uk_100g,glycemic-index_100g,water-hardness_100g
0,3087,http://world-en.openfoodfacts.org/product/0000...,openfoodfacts-contributors,1474103866,2016-09-17T09:17:46Z,1474103893,2016-09-17T09:18:13Z,Farine de blé noir,NaN,1kg,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,4530,http://world-en.openfoodfacts.org/product/0000...,usda-ndb-import,1489069957,2017-03-09T14:32:37Z,1489069957,2017-03-09T14:32:37Z,Banana Chips Sweetened (Whole),NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,14.0,14.0,NaN,NaN
2,4559,http://world-en.openfoodfacts.org/product/0000...,usda-ndb-import,1489069957,2017-03-09T14:32:37Z,1489069957,2017-03-09T14:32:37Z,Peanuts,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN
3,16087,http://world-en.openfoodfacts.org/product/0000...,usda-ndb-import,1489055731,2017-03-09T10:35:31Z,1489055731,2017-03-09T10:35:31Z,Organic Salted Nut Mix,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,12.0,12.0,NaN,NaN
4,16094,http://world-en.openfoodfacts.org/product/0000...,usda-ndb-import,1489055653,2017-03-09T10:34:13Z,1489055653,2017-03-09T10:34:13Z,Organic Polenta,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

Step 5. What is the number of observations in the dataset?

In [41]:
db_food.shape

(356027, 163)

In [42]:
db_food.shape[0]

356027

Step 6. What is the number of columns in the dataset?

In [43]:
print(db_food.shape)
print(db_food.shape[1])
print(db_food.info())

(356027, 163)
163
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 356027 entries, 0 to 356026
Columns: 163 entries, code to water-hardness_100g
dtypes: float64(107), object(56)
memory usage: 442.8+ MB
None

Step 7. Print the name of all the columns.

In [44]:
db_food.columns

Index(['code', 'url', 'creator', 'created_t', 'created_datetime',
       'last_modified_t', 'last_modified_datetime', 'product_name',
       'generic_name', 'quantity',
       ...
       'fruits-vegetables-nuts_100g', 'fruits-vegetables-nuts-estimate_100g',
       'collagen-meat-protein-ratio_100g', 'cocoa_100g', 'chlorophyl_100g',
       'carbon-footprint_100g', 'nutrition-score-fr_100g',
       'nutrition-score-uk_100g', 'glycemic-index_100g',
       'water-hardness_100g'],
      dtype='object', length=163)

Step 8. What is the name of 105th column?

In [49]:
col105= db_food.columns[104]
col105

'-glucose_100g'

Step 9. What is the type of the observations of the 105th column?

In [50]:
db_food[col105].dtype

dtype('float64')

Step 10. How is the dataset indexed?

In [48]:
db_food.index

RangeIndex(start=0, stop=356027, step=1)

Step 11. What is the product name of the 19th observation?

In [49]:
db_food.loc[18,'product_name']

'Lotus Organic Brown Jasmine Rice'