# Getting Financial Data - Pandas Datareader
Introduction:

This time you will get data from a website.

In [15]:
!pip install pandas-datareader

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: pandas-datareader in /home/mona/.local/lib/python3.10/site-packages (0.10.0)
Requirement already satisfied: pandas>=0.23 in /home/mona/.local/lib/python3.10/site-packages (from pandas-datareader) (2.3.3)
Requirement already satisfied: requests>=2.19.0 in /home/mona/.local/lib/python3.10/site-packages (from pandas-datareader) (2.33.1)
Requirement already satisfied: lxml in /home/mona/.local/lib/python3.10/site-packages (from pandas-datareader) (6.0.2)
Requirement already satisfied: numpy>=1.22.4 in /home/mona/.local/lib/python3.10/site-packages (from pandas>=0.23->pandas-datareader) (2.2.6)
Requirement already satisfied: pytz>=2020.1 in /home/mona/.local/lib/python3.10/site-packages (from pandas>=0.23->pandas-datareader) (2026.1.post1)
Requirement already satisfied: python-dateutil>=2.8.2 in /home/mona/.local/lib/python3.10/site-packages (from pandas>=0.23->pandas-datareader) (2.9.0.post0)
Requirement already satisfied: tzdata>=2022.7 in /home/mona/.local/lib/python3.10/site-packages (from pandas>=0.23->pandas-datareader) (2025.3)
Requirement already satisfied: charset_normalizer<4,>=2 in /home/mona/.local/lib/python3.10/site-packages (from requests>=2.19.0->pandas-datareader) (3.4.7)
Requirement already satisfied: certifi>=2023.5.7 in /home/mona/.local/lib/python3.10/site-packages (from requests>=2.19.0->pandas-datareader) (2026.2.25)
Requirement already satisfied: urllib3<3,>=1.26 in /usr/lib/python3/dist-packages (from requests>=2.19.0->pandas-datareader) (1.26.5)
Requirement already satisfied: idna<4,>=2.5 in /usr/lib/python3/dist-packages (from requests>=2.19.0->pandas-datareader) (3.3)
Requirement already satisfied: six>=1.5 in /usr/lib/python3/dist-packages (from python-dateutil>=2.8.2->pandas>=0.23->pandas-datareader) (1.16.0)

In [16]:
!pip install yfinance

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: yfinance in /home/mona/.local/lib/python3.10/site-packages (1.2.2)
Requirement already satisfied: pytz>=2022.5 in /home/mona/.local/lib/python3.10/site-packages (from yfinance) (2026.1.post1)
Requirement already satisfied: requests>=2.31 in /home/mona/.local/lib/python3.10/site-packages (from yfinance) (2.33.1)
Requirement already satisfied: curl_cffi>=0.15 in /home/mona/.local/lib/python3.10/site-packages (from yfinance) (0.15.0)
Requirement already satisfied: numpy>=1.16.5 in /home/mona/.local/lib/python3.10/site-packages (from yfinance) (2.2.6)
Requirement already satisfied: beautifulsoup4>=4.11.1 in /home/mona/.local/lib/python3.10/site-packages (from yfinance) (4.14.3)
Requirement already satisfied: protobuf>=3.19.0 in /home/mona/.local/lib/python3.10/site-packages (from yfinance) (7.34.0)
Requirement already satisfied: peewee>=3.16.2 in /home/mona/.local/lib/python3.10/site-packages (from yfinance) (4.0.4)
Requirement already satisfied: platformdirs>=2.0.0 in /home/mona/.local/lib/python3.10/site-packages (from yfinance) (4.9.4)
Requirement already satisfied: multitasking>=0.0.7 in /home/mona/.local/lib/python3.10/site-packages (from yfinance) (0.0.12)
Requirement already satisfied: websockets>=13.0 in /home/mona/.local/lib/python3.10/site-packages (from yfinance) (16.0)
Requirement already satisfied: pandas>=1.3.0 in /home/mona/.local/lib/python3.10/site-packages (from yfinance) (2.3.3)
Requirement already satisfied: frozendict>=2.3.4 in /home/mona/.local/lib/python3.10/site-packages (from yfinance) (2.4.7)
Requirement already satisfied: typing-extensions>=4.0.0 in /home/mona/.local/lib/python3.10/site-packages (from beautifulsoup4>=4.11.1->yfinance) (4.15.0)
Requirement already satisfied: soupsieve>=1.6.1 in /usr/lib/python3/dist-packages (from beautifulsoup4>=4.11.1->yfinance) (2.3.1)
Requirement already satisfied: certifi>=2024.2.2 in /home/mona/.local/lib/python3.10/site-packages (from curl_cffi>=0.15->yfinance) (2026.2.25)
Requirement already satisfied: cffi>=2.0.0 in /home/mona/.local/lib/python3.10/site-packages (from curl_cffi>=0.15->yfinance) (2.0.0)
Requirement already satisfied: rich in /home/mona/.local/lib/python3.10/site-packages (from curl_cffi>=0.15->yfinance) (15.0.0)
Requirement already satisfied: python-dateutil>=2.8.2 in /home/mona/.local/lib/python3.10/site-packages (from pandas>=1.3.0->yfinance) (2.9.0.post0)
Requirement already satisfied: tzdata>=2022.7 in /home/mona/.local/lib/python3.10/site-packages (from pandas>=1.3.0->yfinance) (2025.3)
Requirement already satisfied: charset_normalizer<4,>=2 in /home/mona/.local/lib/python3.10/site-packages (from requests>=2.31->yfinance) (3.4.7)
Requirement already satisfied: urllib3<3,>=1.26 in /usr/lib/python3/dist-packages (from requests>=2.31->yfinance) (1.26.5)
Requirement already satisfied: idna<4,>=2.5 in /usr/lib/python3/dist-packages (from requests>=2.31->yfinance) (3.3)
Requirement already satisfied: pycparser in /home/mona/.local/lib/python3.10/site-packages (from cffi>=2.0.0->curl_cffi>=0.15->yfinance) (3.0)
Requirement already satisfied: six>=1.5 in /usr/lib/python3/dist-packages (from python-dateutil>=2.8.2->pandas>=1.3.0->yfinance) (1.16.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /home/mona/.local/lib/python3.10/site-packages (from rich->curl_cffi>=0.15->yfinance) (2.20.0)
Requirement already satisfied: markdown-it-py>=2.2.0 in /home/mona/.local/lib/python3.10/site-packages (from rich->curl_cffi>=0.15->yfinance) (4.0.0)
Requirement already satisfied: mdurl~=0.1 in /home/mona/.local/lib/python3.10/site-packages (from markdown-it-py>=2.2.0->rich->curl_cffi>=0.15->yfinance) (0.1.2)

### Step 1. Import the necessary libraries

In [14]:
import numpy as np
import pandas as pd

# package to extract data from various Internet sources into a DataFrame
# make sure you have it installed
import pandas_datareader.data as web

# package for dates
import datetime as dt

### Step 2. Create your time range (start and end variables). The start date should be 01/01/2015 and the end should today (whatever your today is).

In [8]:
start = dt.datetime(2015, 1, 1)
end = dt.datetime.today()

print(start)

2015-01-01 00:00:00

### Step 3. Get an API key for one of the APIs that are supported by Pandas Datareader, preferably for AlphaVantage.

If you do not have an API key for any of the supported APIs, it is easiest to get one for AlphaVantage. (Note that the API key is shown directly after the signup. You do not receive it via e-mail.)

(For a full list of the APIs that are supported by Pandas Datareader, see here. As the APIs are provided by third parties, this list may change.)

### Step 4. Use Pandas Datarader to read the daily time series for the Apple stock (ticker symbol AAPL) between 01/01/2015 and today, assign it to df_apple and print it.

In [13]:
df_apple = web.DataReader(name="AAPL",
                          data_source="av-daily",
                          start=start,
                          end=end,
                          api_key="9CJLOFSSODR0APFM")

df_apple

RemoteDataError:  Their was an issue from the data vendor side, here is their response: {'Information': 'Thank you for using Alpha Vantage! The outputsize=full parameter value is a premium feature for the TIME_SERIES_DAILY endpoint. You may subscribe to any of the premium plans at https://www.alphavantage.co/premium/ to instantly unlock all premium features'}

In [18]:
import yfinance as yf

df_apple = yf.download("AAPL", start=start, end=end)

df_apple

[*********************100%***********************]  1 of 1 completed

Price            Close        High         Low        Open     Volume
Ticker            AAPL        AAPL        AAPL        AAPL       AAPL
Date
2015-01-02   24.214895   24.682228   23.776355   24.671153  212818400
2015-01-05   23.532722   24.064285   23.346676   23.984551  257142000
2015-01-06   23.534941   23.794077   23.173920   23.596956  263188400
2015-01-07   23.864950   23.964618   23.632391   23.743133  160423600
2015-01-08   24.781895   24.839481   24.075359   24.192747  237458000
...                ...         ...         ...         ...        ...
2026-04-10  260.480011  262.190002  259.019989  259.980011   31291500
2026-04-13  259.200012  260.179993  256.660004  259.730011   36234700
2026-04-14  258.829987  261.929993  257.190002  259.250000   48370700
2026-04-15  266.429993  266.559998  257.809998  258.160004   49735000
2026-04-16  263.980011  267.160004  261.269989  266.799988   19296883

[2838 rows x 5 columns]

### Step 5. Add a new column "stock" to the dataframe and add the ticker symbol

In [19]:
df_apple["stock"] = "AAPL"
df_apple

Price            Close        High         Low        Open     Volume stock
Ticker            AAPL        AAPL        AAPL        AAPL       AAPL
Date
2015-01-02   24.214895   24.682228   23.776355   24.671153  212818400  AAPL
2015-01-05   23.532722   24.064285   23.346676   23.984551  257142000  AAPL
2015-01-06   23.534941   23.794077   23.173920   23.596956  263188400  AAPL
2015-01-07   23.864950   23.964618   23.632391   23.743133  160423600  AAPL
2015-01-08   24.781895   24.839481   24.075359   24.192747  237458000  AAPL
...                ...         ...         ...         ...        ...   ...
2026-04-10  260.480011  262.190002  259.019989  259.980011   31291500  AAPL
2026-04-13  259.200012  260.179993  256.660004  259.730011   36234700  AAPL
2026-04-14  258.829987  261.929993  257.190002  259.250000   48370700  AAPL
2026-04-15  266.429993  266.559998  257.809998  258.160004   49735000  AAPL
2026-04-16  263.980011  267.160004  261.269989  266.799988   19296883  AAPL

[2838 rows x 6 columns]

### Step 6. Repeat the two previous steps for a few other stocks, always creating a new dataframe: Tesla, IBM and Microsoft. (Ticker symbols TSLA, IBM and MSFT.)

In [20]:
# Tesla
df_tesla = web.DataReader(name="TSLA",
                          data_source="av-daily",
                          start=start,
                          end=end,
                          api_key="your_alpha_vantage_api_key_goes_here")

df_tesla["stock"] = "TSLA"

# IBM
df_ibm = web.DataReader(name="IBM",
                        data_source="av-daily",
                        start=start,
                        end=end,
                        api_key="your_alpha_vantage_api_key_goes_here")

df_ibm["stock"] = "IBM"

# Microsoft
df_microsoft = web.DataReader(name="MSFT",
                              data_source="av-daily",
                              start=start,
                              end=end,
                              api_key="your_alpha_vantage_api_key_goes_here")

df_microsoft["stock"] = "MSFT"

RemoteDataError:  Their was an issue from the data vendor side, here is their response: {'Information': 'Thank you for using Alpha Vantage! The outputsize=full parameter value is a premium feature for the TIME_SERIES_DAILY endpoint. You may subscribe to any of the premium plans at https://www.alphavantage.co/premium/ to instantly unlock all premium features'}

In [21]:
df_tesla = yf.download("TSLA", start=start, end=end)
df_tesla["stock"] = "TSLA"


df_ibm = yf.download("IBM", start=start, end=end)
df_ibm["stock"] = "IBM"


df_microsoft = yf.download("MSFT", start=start, end=end)
df_microsoft["stock"] = "MSFT"


df_tesla.head()

[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed

Price           Close       High        Low       Open    Volume stock
Ticker           TSLA       TSLA       TSLA       TSLA      TSLA
Date
2015-01-02  14.620667  14.883333  14.217333  14.858000  71466000  TSLA
2015-01-05  14.006000  14.433333  13.810667  14.303333  80527500  TSLA
2015-01-06  14.085333  14.280000  13.614000  14.004000  93928500  TSLA
2015-01-07  14.063333  14.318667  13.985333  14.223333  44526000  TSLA
2015-01-08  14.041333  14.253333  14.000667  14.187333  51637500  TSLA

### Step 7. Combine the four separate dataFrames into one combined dataFrame df that holds the information for all four stocks

In [23]:
frames = [df_apple, df_tesla, df_ibm, df_microsoft]

df = pd.concat(frames)
df

Price,Close,High,Low,Open,Volume,stock,Close,High,Low,Open,...,Close,High,Low,Open,Volume,Close,High,Low,Open,Volume
Ticker,AAPL,AAPL,AAPL,AAPL,AAPL,,TSLA,TSLA,TSLA,TSLA,...,IBM,IBM,IBM,IBM,IBM,MSFT,MSFT,MSFT,MSFT,MSFT
Date,,,,,,,,,,,,,,,,,,,,,
2015-01-02,24.214895,24.682228,23.776355,24.671153,212818400.0,AAPL,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2015-01-05,23.532722,24.064285,23.346676,23.984551,257142000.0,AAPL,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2015-01-06,23.534941,23.794077,23.173920,23.596956,263188400.0,AAPL,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2015-01-07,23.864950,23.964618,23.632391,23.743133,160423600.0,AAPL,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2015-01-08,24.781895,24.839481,24.075359,24.192747,237458000.0,AAPL,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2026-04-10,NaN,NaN,NaN,NaN,NaN,MSFT,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,370.869995,375.640015,370.029999,372.980011,28111100.0
2026-04-13,NaN,NaN,NaN,NaN,NaN,MSFT,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,384.369995,384.540009,371.019989,373.609985,35745800.0
2026-04-14,NaN,NaN,NaN,NaN,NaN,MSFT,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,393.109985,394.690002,386.519989,387.920013,37504500.0
2026-04-15,NaN,NaN,NaN,NaN,NaN,MSFT,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,411.220001,414.369995,396.730011,398.000000,44793300.0
2026-04-16,NaN,NaN,NaN,NaN,NaN,MSFT,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,419.970093,420.559998,412.140015,419.989990,20049624.0

### Step 8. Shift the stock column into the index (making it a multi-level index consisting of the ticker symbol and the date).

In [24]:
df.set_index(keys="stock", append=True, inplace=True)
df

,Price,Close,High,Low,Open,Volume,Close,High,Low,Open,Volume,Close,High,Low,Open,Volume,Close,High,Low,Open,Volume
,Ticker,AAPL,AAPL,AAPL,AAPL,AAPL,TSLA,TSLA,TSLA,TSLA,TSLA,IBM,IBM,IBM,IBM,IBM,MSFT,MSFT,MSFT,MSFT,MSFT
Date,stock,,,,,,,,,,,,,,,,,,,,
2015-01-02,AAPL,24.214895,24.682228,23.776355,24.671153,212818400.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2015-01-05,AAPL,23.532722,24.064285,23.346676,23.984551,257142000.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2015-01-06,AAPL,23.534941,23.794077,23.173920,23.596956,263188400.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2015-01-07,AAPL,23.864950,23.964618,23.632391,23.743133,160423600.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2015-01-08,AAPL,24.781895,24.839481,24.075359,24.192747,237458000.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2026-04-10,MSFT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,370.869995,375.640015,370.029999,372.980011,28111100.0
2026-04-13,MSFT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,384.369995,384.540009,371.019989,373.609985,35745800.0
2026-04-14,MSFT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,393.109985,394.690002,386.519989,387.920013,37504500.0
2026-04-15,MSFT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,411.220001,414.369995,396.730011,398.000000,44793300.0
2026-04-16,MSFT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,419.970093,420.559998,412.140015,419.989990,20049624.0

### Step 7. Create a dataFrame called vol, with the volume values.

In [37]:
vol = df['Volume']

vol = pd.DataFrame(vol)

vol

Ticker                   AAPL  TSLA  IBM        MSFT
Date       stock
2015-01-02 AAPL   212818400.0   NaN  NaN         NaN
2015-01-05 AAPL   257142000.0   NaN  NaN         NaN
2015-01-06 AAPL   263188400.0   NaN  NaN         NaN
2015-01-07 AAPL   160423600.0   NaN  NaN         NaN
2015-01-08 AAPL   237458000.0   NaN  NaN         NaN
...                       ...   ...  ...         ...
2026-04-10 MSFT           NaN   NaN  NaN  28111100.0
2026-04-13 MSFT           NaN   NaN  NaN  35745800.0
2026-04-14 MSFT           NaN   NaN  NaN  37504500.0
2026-04-15 MSFT           NaN   NaN  NaN  44793300.0
2026-04-16 MSFT           NaN   NaN  NaN  20049624.0

[11352 rows x 4 columns]

### Step 8. Aggregate the data of volume to weekly.

Hint: Be careful to not sum data from the same week of 2015 and other years.

In [54]:
vol_flat = vol.reset_index()

vol_flat['year'] = vol_flat['Date'].dt.year
vol_flat['week'] = vol_flat['Date'].dt.isocalendar().week

vol_weekly = vol_flat.groupby(['year', 'week']).sum(numeric_only=True)

vol_weekly.head(15)

Ticker             aapl         tsla         ibm         msft
year week
2015 1     2.128184e+08   71466000.0   5779673.0   27913900.0
     2     1.133010e+09  340644000.0  25578884.0  158825300.0
     3     1.216906e+09  461988000.0  24329751.0  157088200.0
     4     7.949480e+08  243175500.0  32682062.0  137352600.0
     5     1.863371e+09  235803000.0  34442689.0  437786800.0
     6     1.083029e+09  285714000.0  23472449.0  215214500.0
     7     1.212827e+09  607089000.0  19000590.0  172848000.0
     8     7.774196e+08  267441000.0  14759373.0  118131900.0
     9     1.472865e+09  440518500.0  23996705.0  150315300.0
     10    9.877540e+08  422487000.0  22089218.0  148863600.0
     11    1.306056e+09  403123500.0  27338465.0  221483200.0
     12    1.066692e+09  421327500.0  26866615.0  216925300.0
     13    8.373052e+08  371172000.0  24663634.0  167126300.0
     14    6.481272e+08  358816500.0  17537027.0  144289700.0
     15    7.288300e+08  464620500.0  14557391.0  146532400.0

### Step 9. Find all the volume traded in the year of 2015

In [57]:
total_volume_2015 = vol_weekly.loc[2015].sum().sum()

print(f"Total volume traded in 2015: {total_volume_2015}")

Total volume traded in 2015: 78803361900.0

In [56]:
vol_2015_display = vol_weekly.loc[2015].sum().to_frame().T

vol_2015_display.index = [2015]
vol_2015_display.index.name = 'year'

vol_2015_display

Ticker          aapl          tsla           ibm          msft
year
2015    5.226420e+10  1.632327e+10  1.156439e+09  9.059456e+09