Name: Mona Mashtaa

# MPG Cars

Introduction:

The following exercise utilizes data from [UC Irvine Machine Learning Repository](https://archive.ics.uci.edu/ml/datasets/Auto+MPG)

## Step 1. Import the necessary libraries

In [33]:
import pandas as pd

## Step 2. Import the first dataset cars1 and cars2.

## Step 3. Assign each to a variable called cars1 and cars2

In [34]:
car1 = pd.read_csv('https://raw.githubusercontent.com/guipsamora/pandas_exercises/master/05_Merge/Auto_MPG/cars1.csv')
car2 = pd.read_csv('https://raw.githubusercontent.com/guipsamora/pandas_exercises/master/05_Merge/Auto_MPG/cars2.csv')

## Step 4. Oops, it seems our first dataset has some unnamed blank columns, fix cars1

In [35]:
car1.head()

,mpg,cylinders,displacement,horsepower,weight,acceleration,model,origin,car,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13
0,18.0,8,307,130,3504,12.0,70,1,chevrolet chevelle malibu,NaN,NaN,NaN,NaN,NaN
1,15.0,8,350,165,3693,11.5,70,1,buick skylark 320,NaN,NaN,NaN,NaN,NaN
2,18.0,8,318,150,3436,11.0,70,1,plymouth satellite,NaN,NaN,NaN,NaN,NaN
3,16.0,8,304,150,3433,12.0,70,1,amc rebel sst,NaN,NaN,NaN,NaN,NaN
4,17.0,8,302,140,3449,10.5,70,1,ford torino,NaN,NaN,NaN,NaN,NaN

In [36]:
# if it is include the null valu or not
car1.isnull().sum()

mpg               0
cylinders         0
displacement      0
horsepower        0
weight            0
acceleration      0
model             0
origin            0
car               0
Unnamed: 9      198
Unnamed: 10     198
Unnamed: 11     198
Unnamed: 12     198
Unnamed: 13     198
dtype: int64

In [37]:
car1= car1.dropna()

In [38]:
car1.isnull().sum()

mpg             0
cylinders       0
displacement    0
horsepower      0
weight          0
acceleration    0
model           0
origin          0
car             0
Unnamed: 9      0
Unnamed: 10     0
Unnamed: 11     0
Unnamed: 12     0
Unnamed: 13     0
dtype: int64

In [39]:
car2.head()
car2.isnull().sum()

mpg             0
cylinders       0
displacement    0
horsepower      0
weight          0
acceleration    0
model           0
origin          0
car             0
dtype: int64

## Step 5. What is the number of observations in each dataset?

In [40]:
car1.shape[0]

0

In [41]:
car2.shape[0]

200

## Step 6. Join cars1 and cars2 into a single DataFrame called cars

In [21]:
car1.columns

Index(['mpg', 'cylinders', 'displacement', 'horsepower', 'weight',
       'acceleration', 'model', 'origin', 'car', 'Unnamed: 9', 'Unnamed: 10',
       'Unnamed: 11', 'Unnamed: 12', 'Unnamed: 13'],
      dtype='object')

In [22]:
car2.columns

Index(['mpg', 'cylinders', 'displacement', 'horsepower', 'weight',
       'acceleration', 'model', 'origin', 'car'],
      dtype='object')

it is have same columns, so that's easy to join

In [28]:
cars = pd.concat([car1, car2], axis=1)
cars.columns

Index(['mpg', 'cylinders', 'displacement', 'horsepower', 'weight',
       'acceleration', 'model', 'origin', 'car', 'Unnamed: 9', 'Unnamed: 10',
       'Unnamed: 11', 'Unnamed: 12', 'Unnamed: 13', 'mpg', 'cylinders',
       'displacement', 'horsepower', 'weight', 'acceleration', 'model',
       'origin', 'car'],
      dtype='object')

## Step 7. Oops, there is a column missing, called owners. Create a random number Series from 15,000 to 73,000.

In [44]:
import numpy as np
cars['owners'] = np.random.randint(15000, 73001, size=len(cars))

In [45]:
cars.columns

Index(['mpg', 'cylinders', 'displacement', 'horsepower', 'weight',
       'acceleration', 'model', 'origin', 'car', 'Unnamed: 9', 'Unnamed: 10',
       'Unnamed: 11', 'Unnamed: 12', 'Unnamed: 13', 'mpg', 'cylinders',
       'displacement', 'horsepower', 'weight', 'acceleration', 'model',
       'origin', 'car', 'owners'],
      dtype='object')

## Step 8. Add the column owners to cars

In [46]:
cars.head()

,mpg,cylinders,displacement,horsepower,weight,acceleration,model,origin,car,Unnamed: 9,...,mpg,cylinders,displacement,horsepower,weight,acceleration,model,origin,car,owners
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,33.0,4,91,53,1795,17.4,76,3,honda civic,29181
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,20.0,6,225,100,3651,17.7,76,1,dodge aspen se,44503
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,18.0,6,250,78,3574,21.0,76,1,ford granada ghia,15132
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,18.5,6,250,110,3645,16.2,76,1,pontiac ventura sj,64951
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,17.5,6,258,95,3193,17.8,76,1,amc pacer d/l,41347